import { ReactComponent as Copy } from './copy.svg';
import { ReactComponent as Exit } from './exit.svg';
import { ReactComponent as NotificationFilled } from './notification_filled.svg';
import { ReactComponent as ChevronsDown } from './chevrons_down.svg';
import { ReactComponent as LeftOutlined } from './left_outlined.svg';
import { ReactComponent as SwitchArrows } from './switch_arrows.svg';
import { ReactComponent as Reset } from './reset.svg';

import { ReactComponent as MicClose } from './mic_close.svg';
import { ReactComponent as MicDisable } from './mic_disable.svg';
import { ReactComponent as MicLoading } from './mic_loading.svg';
import { ReactComponent as MicNormal } from './mic_normal.svg';

import { ReactComponent as CameraClose } from './camera_close.svg';
import { ReactComponent as CameraDisable } from './camera_disable.svg';
import { ReactComponent as CameraLoading } from './camera_loading.svg';
import { ReactComponent as CameraNormal } from './camera_normal.svg';
import { ReactComponent as CameraCloseSolid } from './camera_close_solid.svg';

import { ReactComponent as Hand } from './hand.svg';
import { ReactComponent as Setting } from './setting.svg';

import { ReactComponent as Board } from './board.svg';
import { ReactComponent as BoardDisable } from './board_disable.svg';
import { ReactComponent as Folder } from './folder.svg';
import { ReactComponent as FolderDisable } from './folder_disable.svg';
import { ReactComponent as ScreenShare } from './screen_share.svg';
import { ReactComponent as ScreenShareDisable } from './screen_share_disable.svg';
import { ReactComponent as Media } from './media.svg';
import { ReactComponent as MediaDisable } from './media_disable.svg';
import { ReactComponent as Play } from './play.svg';
import { ReactComponent as Info } from './info.svg';
import { ReactComponent as MediaFile } from './media_file.svg';
import { ReactComponent as ViewSwitch } from './view_switch.svg';

import { ReactComponent as AudioWave } from './audio_wave.svg';
import { ReactComponent as Interaction } from './interaction.svg';
import { ReactComponent as MediaSharePerm } from './media_share_perm.svg';
import { ReactComponent as MuteGroup } from './mute_group.svg';
import { ReactComponent as Next } from './next.svg';
import { ReactComponent as Notify } from './notify.svg';
import { ReactComponent as Remove } from './remove.svg';
import { ReactComponent as ShareScreenPerm } from './share_screen_perm.svg';
import { ReactComponent as User } from './user.svg';
import { ReactComponent as Whiteboard } from './whiteboard.svg';
import { ReactComponent as CalendarOutlined } from './calendar_outlined.svg';
import { ReactComponent as CalendarFilled } from './calendar_filled.svg';
import { ReactComponent as Announcement } from './announcement.svg';
import { ReactComponent as Edit } from './edit.svg';
import { ReactComponent as Tools } from './tools.svg';
import { ReactComponent as MuteFilled } from './mute_filled.svg';
import { ReactComponent as MuteOutlined } from './mute_outlined.svg';

export const CopySvg = Copy;
export const ExitSvg = Exit;
export const NotificationFilledSvg = NotificationFilled;
export const ChevronsDownSvg = ChevronsDown;
export const LeftOutlinedSvg = LeftOutlined;
export const SwitchArrowsSvg = SwitchArrows;
export const ResetSvg = Reset;
export const MicCloseSvg = MicClose;
export const MicDisableSvg = MicDisable;
export const MicLoadingSvg = MicLoading;
export const MicNormalSvg = MicNormal;
export const CameraCloseSvg = CameraClose;
export const CameraDisableSvg = CameraDisable;
export const CameraLoadingSvg = CameraLoading;
export const CameraNormalSvg = CameraNormal;
export const CameraCloseSolidSvg = CameraCloseSolid;
export const HandSvg = Hand;
export const SettingSvg = Setting;
export const BoardSvg = Board;
export const BoardDisableSvg = BoardDisable;
export const FolderSvg = Folder;
export const FolderDisableSvg = FolderDisable;
export const ScreenShareSvg = ScreenShare;
export const ScreenShareDisableSvg = ScreenShareDisable;
export const MediaSvg = Media;
export const MediaDisableSvg = MediaDisable;
export const MediaFileSvg = MediaFile;
export const PlaySvg = Play;
export const InfoSvg = Info;
export const ViewSwitchSvg = ViewSwitch;
export const AudioWaveSvg = AudioWave;
export const InteractionSvg = Interaction;
export const MediaSharePermSvg = MediaSharePerm;
export const MuteGroupSvg = MuteGroup;
export const NextSvg = Next;
export const NotifySvg = Notify;
export const RemoveSvg = Remove;
export const ShareScreenPermSvg = ShareScreenPerm;
export const UserSvg = User;
export const WhiteboardSvg = Whiteboard;
export const CalendarOutlinedSvg = CalendarOutlined;
export const CalendarFilledSvg = CalendarFilled;
export const AnnouncementSvg = Announcement;
export const EditSvg = Edit;
export const ToolsSvg = Tools;
export const MuteFilledSvg = MuteFilled;
export const MuteOutlinedSvg = MuteOutlined;
