import { ReactComponent as Copy } from './copy.svg';
import { ReactComponent as Exit } from './exit.svg';
import { ReactComponent as NotificationFilled } from './notification_filled.svg';
import { ReactComponent as ChevronsDown } from './chevrons_down.svg';
import { ReactComponent as LeftOutline } from './left_outling.svg';
import { ReactComponent as SwitchArrows } from './switch_arrows.svg';
import { ReactComponent as Reset } from './reset.svg';

import { ReactComponent as MicClose } from './mic_close.svg';
import { ReactComponent as MicDisable } from './mic_disable.svg';
import { ReactComponent as MicLoading } from './mic_loading.svg';
import { ReactComponent as MicNormal } from './mic_normal.svg';

import { ReactComponent as CameraClose } from './camera_close.svg';
import { ReactComponent as CameraDisable } from './camera_disable.svg';
import { ReactComponent as CameraLoading } from './camera_loading.svg';
import { ReactComponent as CameraNormal } from './camera_normal.svg';
import { ReactComponent as CameraCloseSolid } from './camera_close_solid.svg';

import { ReactComponent as Hand } from './hand.svg';
import { ReactComponent as Setting } from './setting.svg';

import { ReactComponent as Board } from './board.svg';
import { ReactComponent as BoardDisable } from './board_disable.svg';
import { ReactComponent as Folder } from './folder.svg';
import { ReactComponent as FolderDisable } from './folder_disable.svg';
import { ReactComponent as ScreenShare } from './screen_share.svg';
import { ReactComponent as ScreenShareDisable } from './screen_share_disable.svg';
import { ReactComponent as Media } from './media.svg';
import { ReactComponent as MediaDisable } from './media_disable.svg';
import { ReactComponent as Play } from './play.svg';
import { ReactComponent as Info } from './info.svg';
import { ReactComponent as MediaFile } from './media_file.svg';
import { ReactComponent as ViewSwitch } from './view_switch.svg';

export const CopySvg = Copy;
export const ExitSvg = Exit;
export const NotificationFilledSvg = NotificationFilled;
export const ChevronsDownSvg = ChevronsDown;
export const LeftOutlineSvg = LeftOutline;
export const SwitchArrowsSvg = SwitchArrows;
export const ResetSvg = Reset;
export const MicCloseSvg = MicClose;
export const MicDisableSvg = MicDisable;
export const MicLoadingSvg = MicLoading;
export const MicNormalSvg = MicNormal;
export const CameraCloseSvg = CameraClose;
export const CameraDisableSvg = CameraDisable;
export const CameraLoadingSvg = CameraLoading;
export const CameraNormalSvg = CameraNormal;
export const CameraCloseSolidSvg = CameraCloseSolid;
export const HandSvg = Hand;
export const SettingSvg = Setting;
export const BoardSvg = Board;
export const BoardDisableSvg = BoardDisable;
export const FolderSvg = Folder;
export const FolderDisableSvg = FolderDisable;
export const ScreenShareSvg = ScreenShare;
export const ScreenShareDisableSvg = ScreenShareDisable;
export const MediaSvg = Media;
export const MediaDisableSvg = MediaDisable;
export const MediaFileSvg = MediaFile;
export const PlaySvg = Play;
export const InfoSvg = Info;
export const ViewSwitchSvg = ViewSwitch;
